#!/bin/sh -e

set -x

(cd src/pydantic-ai-absurd && uv run coverage report --show-missing --skip-covered --fail-under=100)

(cd src/agent-sessions && uv run coverage report --show-missing --skip-covered --fail-under=100)
